spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:transaction-data-aggregation
    username: sa
    password:
    data: classpath:/data.sql
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

cloud:
  aws:
    credentials:
      instanceProfile: true
    s3:
      bucket: used-trading-api-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false