spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/used-trading-api
    username: sa
    password:
    data: classpath:/data.sql
    initialization-mode: always

cloud:
  aws:
    credentials:
      instanceProfile: true
    s3:
      bucket: used-trading-api-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false